version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master


volumes:
    postgres-volume: