version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres-volume: